const sqlite= require('sqlite3')
const db= new sqlite.Database('football.db')
const createUserTable= `CREATE TABLE IF NOT EXISTS USER (ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT NOT NULL,
EMAIL TEXT UNIQUE NOT NULL,
PASSWORD TEXT NOT NULL,
ISADMIN INT)`
 
const createProductsTable=`CREATE TABLE IF NOT EXISTS Products (ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT NOT NULL,
PRICE REAL NOT NULL,
DESCRIPTION TEXT NOT NULL,
QUANTITY INT NOT NULL)`
 
const createOrderTable =`CREATE TABLE IF NOT EXISTS ORDER (ID INTEGER PRIMARY KEY AUTOINCREMENT,
USER_ID INT NOT NULL,
TOTAL_AMOUNT REAL NOT NULL,
ORDER_DATE TEXT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(ID),
FOREIGN KEY (PRODUCTS_ID) REFERENCES PRODUCTS(ID))`

const createCartTable = `
CREATE TABLE IF NOT EXISTS CART (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(ID))`


 
module.exports={db,createUserTable,createProductsTable,createOrderTable,createCartTable}